name       : pyicu
version    : 1.9.5
release    : 5
source     :
    - https://pypi.python.org/packages/a2/9f/1947f288143191b903e58633ee597cb98bc284de28dafb1231b6f8b67b99/PyICU-1.9.5.tar.gz : 73b052b800861fae3281dbaf9c92d12a81cabf3d31912d94c51862e093ef359b
license    : MIT
component  : programming.python
summary    : Python extension wrapping the ICU C++ API
description: |
    A Python extension wrapping IBM’s International Components for Unicode C++ library (ICU).
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - pkgconfig(icu-i18n)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
