name       : pyicu
version    : '2.5'
release    : 17
source     :
    - https://pypi.io/packages/source/P/PyICU/PyICU-2.5.tar.gz : a120b68c53f769f37bfb70b7e84ca12c3f4ab1e4df43e87a02dff05ae472cdbc
license    : MIT
component  : programming.python
summary    : Python extension wrapping the ICU C++ API
description: |
    A Python extension wrapping IBM’s International Components for Unicode C++ library (ICU).
optimize   : speed
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(icu-i18n)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
