name       : pyicu
version    : '2.9'
release    : 26
source     :
    - https://pypi.io/packages/source/P/PyICU/PyICU-2.9.tar.gz : 3c29d6ce65546157117a1a347a303ecdfcf1a7591ed679fc88cdef4108845878
license    : MIT
component  : programming.python
summary    : Python extension wrapping the ICU C++ API
description: |
    A Python extension wrapping IBM’s International Components for Unicode C++ library (ICU).
optimize   : speed
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(icu-i18n)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
