name       : pyicu
version    : 2.0.6
release    : 13
source     :
    - https://files.pythonhosted.org/packages/9a/bb/724e7dd095c87398664b8eea91fdfd2d5ea9782949e13f2f28bcd5e11a0e/PyICU-2.0.6.tar.gz : dd233737d9fd0399ac5a06382c3c387c257c17bae80aef4e15195bf63d70db67
license    : MIT
component  : programming.python
summary    : Python extension wrapping the ICU C++ API
description: |
    A Python extension wrapping IBM’s International Components for Unicode C++ library (ICU).
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(icu-i18n)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
